version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/luk355-ci/api/v2/package
  api_key:
    secure: 2s1Eodgv5ujtlKkPrFPwGQOOg3zbEepMS1QPQVLG9BeR+ZtK+WUI1W1mtgW7ZXiG
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: y3g9aIW4QYLfxa8zY0UfIfa7MPqcDNmpyzoCuk23WOhiQg/f+9NkcDGrOLq90WLE
  on:
    branch: master
    appveyor_repo_tag: true